/**
 * Direct PDF Generation Test
 * Test PDF generation without using ReportGenerationService
 */

import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

describe('Direct PDF Generation', () => {
  it('should generate PDF similar to ReportGenerationService', (done) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: 'Test Report',
        Author: 'Test Author',
        Creator: 'Test Application'
      }
    });

    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('error', (error) => {
      console.error('PDF Document error:', error);
      done(error);
    });
    
    doc.on('end', () => {
      try {
        const buffer = Buffer.concat(chunks);
        
        // Verify it's a valid PDF
        expect(buffer.length).toBeGreaterThan(0);
        expect(buffer.toString('ascii', 0, 4)).toBe('%PDF');
        
        // Save to file
        const testFile = path.join(process.cwd(), 'test-direct-report.pdf');
        fs.writeFileSync(testFile, buffer);
        
        // Verify file was created
        expect(fs.existsSync(testFile)).toBe(true);
        
        // Clean up
        fs.unlinkSync(testFile);
        
        done();
      } catch (error) {
        done(error);
      }
    });

    try {
      // Add header
      doc.rect(0, 0, doc.page.width, 80)
         .fill('#0ea5e9');

      doc.fillColor('white')
         .fontSize(20)
         .font('Helvetica-Bold')
         .text('Test Company', 50, 25);

      doc.fillColor('black')
         .y = 100;

      // Add title
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .text('Test Report', { align: 'center' });

      doc.moveDown();

      // Add time range
      const startTime = new Date('2024-01-01T00:00:00Z').toLocaleString();
      const endTime = new Date('2024-01-01T01:00:00Z').toLocaleString();
      
      doc.fontSize(12)
         .text(`Report Period: ${startTime} - ${endTime}`, { align: 'center' });
      
      doc.moveDown(2);

      // Add metadata
      const generatedAt = new Date().toLocaleString();
      doc.fontSize(10)
         .font('Helvetica-Bold')
         .text('Generated:', 50, doc.y)
         .font('Helvetica')
         .text(generatedAt, 120, doc.y);

      doc.moveDown(2);

      // Add content
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('Executive Summary');

      doc.moveDown();

      doc.fontSize(12)
         .font('Helvetica')
         .text('This is a test report generated directly using PDFKit.');

      // Add footer
      doc.strokeColor('#cccccc')
         .lineWidth(1)
         .moveTo(50, doc.page.height - 50)
         .lineTo(doc.page.width - 50, doc.page.height - 50)
         .stroke();

      doc.fillColor('#666666')
         .fontSize(8)
         .text(
           `Generated by Test Application on ${generatedAt}`,
           50,
           doc.page.height - 40,
           { align: 'left' }
         );

      doc.end();
    } catch (error) {
      console.error('Error during PDF creation:', error);
      done(error);
    }
  });
});